name = input("What is your name: ") 
print("You are")
print(name)
food = input("What is your favorite food: ")
print("your favorite food is")
print(food)
music = input("What is your favorite music: ")
print("your favorite music is")
print(music)
live = input("Where do you live: ")
print("you live in")
print(live)
country = input("and which country are you from: ")
print("You from")
print(country)
